import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// "use client";

// const getStepsFromLocal = () => {
//   const savedStep =
//     typeof window !== "undefined" ? localStorage?.getItem("currentStep") : null;
//   if (savedStep) {
//     const step = Number(savedStep);
//     if (step === 4) return 1;
//     return step;
//   } else {
//     return 1;
//   }
// };

// export default function Home() {
//   const [steps, setSteps] = useState(getStepsFromLocal());

//   const firstStep = steps === 1;
//   const secondStep = steps === 2;
//   const thirdStep = steps === 3;
//   const final = steps === 4;
//   const handleStep = () => {
//     const nextStep = steps + 1;
//     setSteps(nextStep);

//     if (typeof window !== "undefined") {
//       if (nextStep === 4) {
//         localStorage.setItem("currentStep", 1);
//       } else {
//         localStorage.setItem("currentStep", nextStep);
//       }
//     }
//   };

//   const handleBackButtonn = () => {
//     const prevStep = steps - 1;
//     setSteps(prevStep);
//     if (typeof window !== "undefined") {
//       localStorage.setItem("currentStep", prevStep);
//     }
//   };

//   const handleReset = () => {
//     setSteps(1);
//     if (typeof window !== "undefined") {
//       localStorage.setItem("currentStep", 1);
//     }
//   };

//   return (
//     <div className="w-screen h-screen flex items-center justify-center bg-gray-50">
//       {firstStep && (
//         <div className="absolute w-[480px] h-[655px] top-[182px] left-[480px] rounded-lg flex flex-col justify-between p-8 bg-white border border-gray-100 shadow-sm">
//           <div className="flex flex-col gap-7">
//             <Pineconelogo />

//             <div className="flex flex-col gap-1">
//               <h1 className="text-2xl font-bold text-gray-900">Join Us! 😎</h1>
//               <p className="text-gray-500 text-sm">
//                 Please provide all current information accurately.
//               </p>
//             </div>

//             <div className="flex flex-col gap-4">
//               <div className="flex flex-col gap-1.5">
//                 <label className="text-sm font-semibold text-gray-800">
//                   First name <span className="text-red-500">*</span>
//                 </label>
//                 <input
//                   type="text"
//                   placeholder="Placeholder"
//                   className="w-full h-11 px-3 border border-[#CBD5E1] focus:border-[#3b82f6] rounded-lg text-gray-700 shadow-sm outline-none transition-colors"
//                 />
//               </div>

//               <div className="flex flex-col gap-1.5">
//                 <label className="text-sm font-semibold text-gray-800">
//                   Last name <span className="text-red-500">*</span>
//                 </label>
//                 <input
//                   type="text"
//                   placeholder="Placeholder"
//                   className="w-full h-11 px-3 border border-[#CBD5E1] focus:border-[#3b82f6] rounded-lg text-gray-700 shadow-sm outline-none transition-colors"
//                 />
//               </div>

//               <div className="flex flex-col gap-1.5">
//                 <label className="text-sm font-semibold text-gray-800">
//                   Username <span className="text-red-500">*</span>
//                 </label>
//                 <input
//                   type="text"
//                   placeholder="Placeholder"
//                   className="w-full h-11 px-3 border border-[#CBD5E1] focus:border-[#3b82f6] rounded-lg text-gray-700 shadow-sm outline-none transition-colors"
//                 />
//               </div>
//             </div>
//           </div>

//           <button
//             onClick={handleStep}
//             className="flex items-center justify-center w-full h-11 gap-2 bg-[#111111] text-white rounded-md hover:bg-black transition-colors"
//           >
//             <span className="text-sm font-medium">Continue 1/3</span> <Arrow />
//           </button>
//         </div>
//       )}
