import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// import React, { useState } from 'react';

// export default function App() {
//   const [count, setCount] = useState(0);

//   return (
//     <div className="min-h-screen bg-gray-100 flex items-center justify-center p-4">
//       {/* Карт чингэлэг */}
//       <div className="bg-white p-8 rounded-2xl shadow-xl max-w-md w-full text-center space-y-6">

//         {/* Гарчиг болон тайлбар */}
//         <div className="space-y-2">
//           <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight">
//             React + Tailwind CSS
//           </h1>
//           <p className="text-sm text-gray-500">
//             Код бичихэд маш хялбар, хурдан бөгөөд загварлаг!
//           </p>
//         </div>

//         {/* Төлөв (State) харуулах хэсэг */}
//         <div className="bg-blue-50 p-6 rounded-xl border border-blue-100">
//           <p className="text-xs font-semibold text-blue-600 uppercase tracking-wide">
//             Тоолуур:
//           </p>
//           <p className="text-4xl font-bold text-blue-900 mt-1">
//             {count}
//           </p>
//         </div>

//         {/* Товчлуурууд */}
//         <div className="flex justify-center gap-4">
//           <button
//             onClick={() => setCount(count - 1)}
//             className="px-5 py-2.5 rounded-lg bg-red-500 text-white font-medium hover:bg-red-600 active:scale-95 transition duration-150 shadow-md"
//           >
//             Хасах
//           </button>

//           <button
//             onClick={() => setCount(count + 1)}
//             className="px-5 py-2.5 rounded-lg bg-indigo-600 text-white font-medium hover:bg-indigo-700 active:scale-95 transition duration-150 shadow-md"
//           >
//             Нэмэх
//           </button>
//         </div>

//       </div>
//     </div>
//   );
// }
